--
-- Script was generated by Devart dbForge Studio 2019 for MySQL, Version 8.2.23.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 03.10.2019 10:37:53
-- Server version: 5.7.23
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

--
-- Set default database
--
USE learn;

--
-- Drop procedure `search`
--
DROP PROCEDURE IF EXISTS search;

--
-- Drop table `country`
--
DROP TABLE IF EXISTS country;

--
-- Drop table `language`
--
DROP TABLE IF EXISTS language;

--
-- Drop table `location`
--
DROP TABLE IF EXISTS location;

--
-- Drop table `log`
--
DROP TABLE IF EXISTS log;

--
-- Drop table `program`
--
DROP TABLE IF EXISTS program;

--
-- Drop table `program_cpy01102019`
--
DROP TABLE IF EXISTS program_cpy01102019;

--
-- Drop table `specialty`
--
DROP TABLE IF EXISTS specialty;

--
-- Drop table `specialty_copy`
--
DROP TABLE IF EXISTS specialty_copy;

--
-- Drop table `university`
--
DROP TABLE IF EXISTS university;

--
-- Drop table `university_cpy01102019`
--
DROP TABLE IF EXISTS university_cpy01102019;

--
-- Drop table `university_languages`
--
DROP TABLE IF EXISTS university_languages;

--
-- Drop table `university_programs`
--
DROP TABLE IF EXISTS university_programs;

--
-- Drop table `university_programs_copy01102019`
--
DROP TABLE IF EXISTS university_programs_copy01102019;

--
-- Drop table `university_specialities`
--
DROP TABLE IF EXISTS university_specialities;

--
-- Drop table `university_type`
--
DROP TABLE IF EXISTS university_type;

--
-- Set default database
--
USE learn;

--
-- Create table `university_type`
--
CREATE TABLE university_type (
  id INT(11) NOT NULL AUTO_INCREMENT,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name_ru VARCHAR(255) DEFAULT NULL,
  name_en VARCHAR(255) DEFAULT NULL,
  name_kk VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 6,
AVG_ROW_LENGTH = 4096,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `university_specialities`
--
CREATE TABLE university_specialities (
  id INT(11) NOT NULL AUTO_INCREMENT,
  university_id INT(11) DEFAULT NULL,
  specialty_id INT(11) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 191,
AVG_ROW_LENGTH = 682,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `university_programs_copy01102019`
--
CREATE TABLE university_programs_copy01102019 (
  id INT(11) NOT NULL AUTO_INCREMENT,
  university_id INT(11) DEFAULT NULL,
  program_id INT(11) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 682,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `university_programs`
--
CREATE TABLE university_programs (
  id INT(11) NOT NULL AUTO_INCREMENT,
  university_id INT(11) DEFAULT NULL,
  program_id INT(11) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 99,
AVG_ROW_LENGTH = 167,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `university_languages`
--
CREATE TABLE university_languages (
  id INT(11) NOT NULL AUTO_INCREMENT,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  language_id INT(11) DEFAULT NULL,
  university_id INT(11) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 43,
AVG_ROW_LENGTH = 390,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `university_cpy01102019`
--
CREATE TABLE university_cpy01102019 (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name_ru VARCHAR(1000) DEFAULT NULL,
  name_en VARCHAR(1000) DEFAULT NULL,
  name_kk VARCHAR(1000) DEFAULT NULL,
  country_id INT(11) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  found DATE DEFAULT NULL,
  type_id INT(11) DEFAULT NULL,
  location_id INT(11) DEFAULT NULL,
  url VARCHAR(1000) DEFAULT NULL,
  url_pic VARCHAR(1000) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 43,
AVG_ROW_LENGTH = 390,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `university`
--
CREATE TABLE university (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name_ru VARCHAR(1000) DEFAULT NULL,
  name_en VARCHAR(1000) DEFAULT NULL,
  name_kk VARCHAR(1000) DEFAULT NULL,
  country_id INT(11) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  found DATE DEFAULT NULL,
  type_id INT(11) DEFAULT NULL,
  location_id INT(11) DEFAULT NULL,
  url VARCHAR(1000) DEFAULT NULL,
  url_pic VARCHAR(1000) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 39,
AVG_ROW_LENGTH = 431,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `specialty_copy`
--
CREATE TABLE specialty_copy (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name_ru VARCHAR(255) DEFAULT NULL,
  name_en VARCHAR(255) DEFAULT NULL,
  name_kk VARCHAR(255) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 14,
AVG_ROW_LENGTH = 1170,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `specialty`
--
CREATE TABLE specialty (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name_ru VARCHAR(255) DEFAULT NULL,
  name_en VARCHAR(255) DEFAULT NULL,
  name_kk VARCHAR(255) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 15,
AVG_ROW_LENGTH = 1170,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `program_cpy01102019`
--
CREATE TABLE program_cpy01102019 (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name_ru VARCHAR(1000) DEFAULT NULL,
  name_en VARCHAR(1000) DEFAULT NULL,
  name_kk VARCHAR(1000) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `program`
--
CREATE TABLE program (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name_ru VARCHAR(1000) DEFAULT NULL,
  name_en VARCHAR(1000) DEFAULT NULL,
  name_kk VARCHAR(1000) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 11,
AVG_ROW_LENGTH = 1638,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `log`
--
CREATE TABLE log (
  id INT(11) NOT NULL AUTO_INCREMENT,
  msg VARCHAR(2000) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 49,
AVG_ROW_LENGTH = 1456,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `location`
--
CREATE TABLE location (
  id INT(11) NOT NULL AUTO_INCREMENT,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  name_ru VARCHAR(255) DEFAULT NULL,
  name_en VARCHAR(255) DEFAULT NULL,
  name_kk VARCHAR(255) DEFAULT NULL,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 21,
AVG_ROW_LENGTH = 963,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `language`
--
CREATE TABLE language (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name_ru VARCHAR(50) DEFAULT NULL,
  name_en VARCHAR(255) DEFAULT NULL,
  name_kk VARCHAR(255) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 5,
AVG_ROW_LENGTH = 8192,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

--
-- Create table `country`
--
CREATE TABLE country (
  id INT(11) NOT NULL AUTO_INCREMENT,
  name_ru VARCHAR(255) DEFAULT NULL,
  name_en VARCHAR(255) DEFAULT NULL,
  name_kk VARCHAR(255) DEFAULT NULL,
  created TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  modified TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
)
ENGINE = INNODB,
AUTO_INCREMENT = 15,
AVG_ROW_LENGTH = 1170,
CHARACTER SET utf8,
COLLATE utf8_general_ci;

DELIMITER $$

--
-- Create procedure `search`
--
CREATE PROCEDURE search(IN countryId INT, IN programId INT, IN specialtyId INT, IN languageId INT)
  SQL SECURITY INVOKER
BEGIN
  set @q = 'select u.id, u.name_en \'name\', u.found, ut.name_ru \'type\', lc.name_ru \'location\', u.url, u.url_pic,
     (select GROUP_CONCAT(ll.name_ru SEPARATOR \', \') from university_languages ul 
          join language ll on ll.id = ul.language_id 
      where ul.university_id = u.id 
         group by ul.university_id) \'languages\', 
    (select GROUP_CONCAT(pp.name_ru SEPARATOR \', \') from university_programs up1 
          join program pp on pp.id = up1.program_id 
     where up1.university_id = u.id 
        group by up1.university_id) \'programs\' 
  from university u 
    join location lc on lc.id = u.location_id 
    join university_type ut on ut.id = u.type_id';
  if countryId <> 0 then
    set @q = concat(@q, ' ', 'where u.country_id = ', countryId);
  end if;
  if programId <> 0 then
    if countryId = 0 then
      set @q = concat(@q, ' ', 'where');
    else
       set @q = concat(@q, ' ', 'and');
    end if;
    set @q = concat(@q, ' ', 'EXISTS (
      select * from university_programs up 
      where 
        up.university_id = u.id 
        and up.program_id = ', programId, ')');
  end if;
  if specialtyId <> 0 then
    if countryId = 0 and programId = 0 then
      set @q = concat(@q, ' ', 'where');
    end if;
    if countryId <> 0 or programId <> 0 then
      set @q = concat(@q, ' ', 'and');
    end if;
    set @q = concat(@q, ' ', 'exists (
      select * from university_specialities us
      WHERE 
        us.university_id = u.id
        and us.specialty_id = ', specialtyId ,')');
  end if;
  if languageId <> 0 then
    if countryId = 0 and programId = 0 and specialtyId = 0 then
      set @q = concat(@q, ' ', 'where');
    end if;
    if countryId <> 0 or programId <> 0 or specialtyId <> 0 then
      set @q = concat(@q, ' ', 'and');
    end if;
    set @q = concat(@q, ' ', 'exists (
      select * from university_languages ul
      WHERE 
        ul.university_id = u.id
        and ul.language_id = ', languageId ,')');
  end if;
  set @q = concat(@q, ' ', 'order by u.name_en asc;');
INSERT INTO log (msg)
  VALUES (@q);
  PREPARE dynamic_statement FROM @q;
  EXECUTE dynamic_statement;
  DEALLOCATE PREPARE dynamic_statement;
END
$$

DELIMITER ;

-- 
-- Dumping data for table university_type
--
INSERT INTO university_type VALUES
(1, '2019-09-25 11:17:49', '2019-09-25 11:17:49', 'государственный', NULL, NULL),
(2, '2019-09-25 11:18:03', '2019-09-25 11:18:03', 'частный', NULL, NULL),
(3, '2019-09-25 11:18:17', '2019-09-25 11:18:17', 'независимый', NULL, NULL),
(4, '2019-09-25 11:18:27', '2019-09-25 11:18:27', 'общеобразовательный колледж', NULL, NULL),
(5, '2019-09-25 11:18:39', '2019-09-25 11:18:39', 'языковая школа', NULL, NULL);

-- 
-- Dumping data for table university_specialities
--
INSERT INTO university_specialities VALUES
(1, 1, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(2, 1, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(3, 1, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(4, 1, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(5, 1, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(6, 1, 1, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(7, 1, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(8, 1, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(9, 1, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(10, 1, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(11, 2, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(12, 2, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(13, 2, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(14, 2, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(15, 2, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(16, 4, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(17, 4, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(18, 4, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(19, 4, 11, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(20, 4, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(21, 4, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(22, 8, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(23, 8, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(24, 8, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(25, 8, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(26, 8, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(27, 8, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(28, 10, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(29, 10, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(30, 10, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(31, 10, 13, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(32, 10, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(33, 10, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(34, 10, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(35, 10, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(36, 10, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(37, 10, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(38, 11, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(39, 11, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(40, 11, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(41, 11, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(42, 11, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(43, 11, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(44, 11, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(45, 11, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(46, 11, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(47, 12, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(48, 12, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(49, 12, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(50, 12, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(51, 12, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(52, 12, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(53, 12, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(54, 13, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(55, 13, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(56, 13, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(57, 13, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(58, 13, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(59, 14, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(60, 14, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(61, 14, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(62, 14, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(63, 14, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(64, 14, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(65, 14, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(66, 15, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(67, 15, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(68, 15, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(69, 15, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(70, 15, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(71, 15, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(72, 15, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(73, 16, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(74, 16, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(75, 16, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(76, 16, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(77, 16, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(78, 16, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(79, 16, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(80, 16, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(81, 17, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(82, 17, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(83, 17, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(84, 17, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(85, 17, 11, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(86, 17, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(87, 17, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(88, 17, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(89, 20, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(90, 20, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(91, 20, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(92, 20, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(93, 20, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(94, 20, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(95, 22, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(96, 22, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(97, 22, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(98, 22, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(99, 22, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(100, 22, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(101, 22, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(102, 24, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(103, 24, 11, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(104, 24, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(105, 24, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(106, 24, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(107, 24, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(108, 24, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(109, 26, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(110, 26, 1, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(111, 26, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(112, 26, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(113, 26, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(114, 26, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(115, 26, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(116, 27, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(117, 27, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(118, 27, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(119, 27, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(120, 27, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(121, 27, 12, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(122, 27, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(123, 27, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(124, 28, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(125, 28, 13, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(126, 28, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(127, 28, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(128, 28, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(129, 28, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(130, 28, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(131, 28, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(132, 28, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(133, 29, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(134, 29, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(135, 29, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(136, 29, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(137, 29, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(138, 29, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(139, 29, 11, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(140, 30, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(141, 30, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(142, 30, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(143, 30, 11, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(144, 30, 12, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(145, 30, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(146, 30, 9, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(147, 30, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(148, 30, 14, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(149, 31, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(150, 31, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(151, 31, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(152, 31, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(153, 31, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(154, 33, 11, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(155, 33, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(156, 33, 3, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(157, 33, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(158, 33, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(159, 33, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(160, 33, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(161, 33, 12, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(162, 34, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(163, 34, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(164, 34, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(165, 34, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(166, 35, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(167, 35, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(168, 35, 11, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(169, 35, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(170, 35, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(171, 35, 12, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(172, 35, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(173, 35, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(174, 36, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(175, 36, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(176, 36, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(177, 36, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(178, 37, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(179, 37, 1, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(180, 37, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(181, 37, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(182, 37, 5, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(183, 37, 8, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(184, 37, 4, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(185, 37, 11, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(186, 37, 12, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(187, 38, 10, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(188, 38, 2, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(189, 38, 6, '2019-10-03 09:27:46', '2019-10-03 09:27:46'),
(190, 38, 7, '2019-10-03 09:27:46', '2019-10-03 09:27:46');

-- 
-- Dumping data for table university_programs_copy01102019
--
-- Table learn.university_programs_copy01102019 does not contain any data (it is empty)

-- 
-- Dumping data for table university_programs
--
INSERT INTO university_programs VALUES
(1, 1, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(2, 1, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(3, 1, 9, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(4, 2, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(5, 2, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(6, 3, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(7, 4, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(8, 4, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(9, 4, 3, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(10, 5, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(11, 6, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(12, 7, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(13, 8, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(14, 8, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(15, 8, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(16, 9, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(17, 9, 4, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(18, 10, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(19, 10, 9, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(20, 10, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(21, 11, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(22, 11, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(23, 11, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(24, 12, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(25, 12, 9, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(26, 12, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(27, 12, 4, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(28, 13, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(29, 13, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(30, 13, 3, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(31, 14, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(32, 14, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(33, 14, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(34, 15, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(35, 15, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(36, 15, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(37, 16, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(38, 16, 4, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(39, 16, 5, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(40, 16, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(41, 17, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(42, 17, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(43, 17, 9, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(44, 18, 6, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(45, 19, 4, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(46, 19, 6, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(47, 20, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(48, 20, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(49, 20, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(50, 21, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(51, 22, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(52, 22, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(53, 22, 9, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(54, 22, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(55, 23, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(56, 23, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(57, 24, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(58, 24, 3, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(59, 24, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(60, 24, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(61, 25, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(62, 25, 4, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(63, 25, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(64, 26, 4, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(65, 26, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(66, 26, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(67, 27, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(68, 27, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(69, 27, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(70, 28, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(71, 28, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(72, 28, 9, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(73, 28, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(74, 29, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(75, 29, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(76, 29, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(77, 30, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(78, 30, 3, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(79, 30, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(80, 31, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(81, 31, 3, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(82, 31, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(83, 31, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(84, 32, 1, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(85, 33, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(86, 33, 3, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(87, 34, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(88, 34, 3, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(89, 34, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(90, 35, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(91, 35, 3, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(92, 36, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(93, 36, 4, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(94, 36, 8, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(95, 37, 2, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(96, 37, 3, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(97, 37, 4, '2019-10-01 16:06:51', '2019-10-01 16:06:51'),
(98, 38, 10, '2019-10-01 16:06:51', '2019-10-01 16:06:51');

-- 
-- Dumping data for table university_languages
--
INSERT INTO university_languages VALUES
(1, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 1),
(2, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 2),
(3, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 3),
(4, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 4),
(5, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 5),
(6, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 6),
(7, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 7),
(8, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 8),
(9, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 9),
(10, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 10),
(11, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 11),
(12, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 12),
(13, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 13),
(14, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 14),
(15, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 15),
(16, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 16),
(17, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 17),
(18, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 18),
(19, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 19),
(20, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 20),
(21, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 21),
(22, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 22),
(23, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 23),
(24, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 24),
(25, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 25),
(26, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 26),
(27, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 27),
(28, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 28),
(29, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 29),
(30, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 30),
(31, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 31),
(32, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 32),
(33, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 33),
(34, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 34),
(35, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 35),
(36, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 36),
(37, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 37),
(38, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 38),
(39, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 39),
(40, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 40),
(41, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 41),
(42, '2019-09-25 12:20:52', '2019-09-25 12:20:52', 4, 42);

-- 
-- Dumping data for table university_cpy01102019
--
INSERT INTO university_cpy01102019 VALUES
(1, NULL, 'Algonquin College', NULL, 1, '2019-09-13 09:43:31', '2019-09-25 11:58:31', '1967-01-01', 1, 1, NULL, 'https://globusedu.kz/wp-content/uploads/2018/05/Conestoga-International-College.jpg'),
(2, NULL, 'Bodwell High School & College            ', NULL, 1, '2019-09-13 09:43:31', '2019-09-25 12:02:05', '1991-01-01', 2, 3, 'https://globusedu.kz/canada/bodwell-college-high-school/', 'https://globusedu.kz/wp-content/uploads/2018/05/Conestoga-International-College.jpg'),
(3, NULL, 'Brock University', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(4, NULL, 'Burnaby School District                      ', NULL, 1, '2019-09-13 09:43:31', '2019-09-25 12:03:05', '1906-01-01', 1, 5, 'https://globusedu.kz/burnaby-school-district/', 'https://globusedu.kz/wp-content/uploads/2018/05/Conestoga-International-College.jpg'),
(5, NULL, 'Braemar College                                                  ', NULL, 1, '2019-09-13 09:43:31', '2019-09-26 08:41:59', '1995-01-01', 2, 6, 'https://globusedu.kz/braemar-college/', 'https://globusedu.kz/wp-content/uploads/2018/05/Conestoga-International-College.jpg'),
(6, NULL, 'Branksome Hall', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(7, NULL, 'Columbia College                               ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(8, NULL, 'Columbia International College            ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(9, NULL, 'Centennial College                             ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(10, NULL, 'Conestoga International College', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(11, NULL, 'Centre for Arts and Technology International Study Centre', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(12, NULL, 'Capilano College', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(13, NULL, 'Douglas College', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(14, NULL, 'Durham College  ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(15, NULL, 'Fanshawe College', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(16, NULL, 'Fraser International College (FIC)', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(17, NULL, 'Simon Fraser University', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 10:04:17', NULL, NULL, NULL, NULL, NULL),
(18, NULL, 'George Brown College                         ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(19, NULL, 'Global Village English Centres', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(20, NULL, 'International Language Academy of Canada (ILAC)', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(21, NULL, 'Humber College', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(22, NULL, 'Lakefield College School', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(23, NULL, 'Niagara College                                  ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(24, NULL, 'Pickering College', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(25, NULL, 'Royal Roads University', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(26, NULL, 'Rutherford Canadian School                       ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(27, NULL, 'SAIT Polytechnic', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(28, NULL, 'St.Lawrence College', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(29, NULL, 'Seneca College                                  ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(30, NULL, 'Stenberg College', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(31, NULL, 'Sheridan College', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(32, NULL, 'Thompson Rivers University                 ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(33, NULL, 'Trent University', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(34, NULL, 'Trinity College School', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(35, NULL, 'University of Victoria', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(36, NULL, 'University of Guelph', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(37, NULL, 'University of British Columbia (UBC)', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 10:05:48', NULL, NULL, NULL, NULL, NULL),
(38, NULL, 'University of Manitoba', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(39, NULL, 'International College of Manitoba (ICM)', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(40, NULL, 'University of Toronto', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(41, NULL, 'UBC Vantage College                           ', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL),
(42, NULL, 'Vancouver Film Academy', NULL, 1, '2019-09-13 09:43:31', '2019-09-13 09:43:31', NULL, NULL, NULL, NULL, NULL);

-- 
-- Dumping data for table university
--
INSERT INTO university VALUES
(1, NULL, 'Algonquin College', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1967-01-01', 1, 1, 'https://globusedu.kz/canada/algonquin-college/', 'https://globusedu.kz/wp-content/uploads/2019/09/Algonquin-College.jpg'),
(2, NULL, 'Alexander College', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '2006-01-01', 2, 2, 'https://globusedu.kz/canada/alexander-college/', 'https://globusedu.kz/wp-content/uploads/2019/09/Alexander-College.jpg'),
(3, NULL, 'Bodwell High School & College           ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1991-01-01', 2, 3, 'https://globusedu.kz/canada/bodwell-college-high-school/', 'https://globusedu.kz/wp-content/uploads/2019/10/Bodwell-High-School.jpg'),
(4, NULL, 'Brock University', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1964-01-01', 1, 4, 'https://globusedu.kz/canada/brock-university/', 'https://globusedu.kz/wp-content/uploads/2019/09/Brock-University.jpg'),
(5, NULL, 'Burnaby School District                     ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1906-01-01', 1, 5, 'https://globusedu.kz/canada/burnaby-school-district/', 'https://globusedu.kz/wp-content/uploads/2019/10/Burnaby-School-District.jpg'),
(6, NULL, 'Braemar College                                                 ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1995-01-01', 2, 6, 'https://globusedu.kz/canada/braemar-college/', 'https://globusedu.kz/wp-content/uploads/2019/10/Braemar-College.jpg'),
(7, NULL, 'Branksome Hall', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1903-01-01', 2, 6, 'https://globusedu.kz/canada/branksome-hall/', 'https://globusedu.kz/wp-content/uploads/2019/10/Branksome-Hall.jpg'),
(8, NULL, 'Columbia College                              ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1936-01-01', 3, 3, 'https://globusedu.kz/canada/columbia-college/', 'https://globusedu.kz/wp-content/uploads/2018/12/Columbia-College-1-e1545226967692.jpg"'),
(9, NULL, 'Columbia International College           ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1979-01-01', 2, 7, 'https://globusedu.kz/canada/columbia-international-college/', 'https://globusedu.kz/wp-content/uploads/2019/10/Columbia-International-College.jpg'),
(10, NULL, 'Centennial College                            ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1966-01-01', 1, 6, 'https://globusedu.kz/canada/centennial-college/', 'https://globusedu.kz/wp-content/uploads/2019/10/Centennial-College.jpg'),
(11, NULL, 'Conestoga International College', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1967-01-01', 1, 8, 'https://globusedu.kz/canada/conestoga-international-college/', 'https://globusedu.kz/wp-content/uploads/2018/05/Conestoga-International-College.jpg'),
(12, NULL, 'Capilano University', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1968-01-01', 1, 3, 'https://globusedu.kz/canada/capilano-university/', 'https://globusedu.kz/wp-content/uploads/2019/09/Capilano-University.jpg'),
(13, NULL, 'Douglas College', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1970-01-01', 1, 3, 'https://globusedu.kz/canada/douglas-college/', 'https://globusedu.kz/wp-content/uploads/2019/09/Douglas-College.jpg'),
(14, NULL, 'Durham College ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1967-01-01', 1, 9, 'https://globusedu.kz/canada/durham-college/', 'https://globusedu.kz/wp-content/uploads/2018/12/Durham-College2.jpg'),
(15, NULL, 'Fanshawe College', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1967-01-01', 4, 10, 'https://globusedu.kz/canada/fanshawe-college/', 'https://globusedu.kz/wp-content/uploads/2019/09/fanshawe_college-1.jpg'),
(16, NULL, 'Fraser International College (FIC) (Simon Fraser University)', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1965-01-01', 1, 3, 'https://globusedu.kz/canada/fraser-international-college/', 'https://globusedu.kz/wp-content/uploads/2019/10/Simon-Fraser-University.jpg'),
(17, NULL, 'George Brown College                        ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1967-01-01', 1, 6, 'https://globusedu.kz/canada/george-brown-college/', 'https://globusedu.kz/wp-content/uploads/2018/12/georgebrown.jpg'),
(18, NULL, 'Global Village English Centres', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1996-01-01', 2, 11, 'https://globusedu.kz/canada/global-village-english-centres/', 'https://globusedu.kz/wp-content/uploads/2019/10/Global-Village-English-Centres.jpg'),
(19, NULL, 'International Language Academy of Canada (ILAC)', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1998-01-01', 5, 12, 'https://globusedu.kz/canada/ilac-international-language-academy-of-canada/', 'https://globusedu.kz/wp-content/uploads/2019/05/ilac.jpg'),
(20, NULL, 'Humber College', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1967-01-01', 1, 6, 'https://globusedu.kz/canada/humber-college/', 'https://globusedu.kz/wp-content/uploads/2019/08/humber-college.jpg'),
(21, NULL, 'Lakefield College School', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1879-01-01', 2, 13, 'https://globusedu.kz/canada/lakefield-college-school/', 'https://globusedu.kz/wp-content/uploads/2019/10/Lakefield-College-School.jpg'),
(22, NULL, 'Niagara College                                 ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1967-01-01', 1, 14, 'https://globusedu.kz/canada/niagara-college/', 'https://globusedu.kz/wp-content/uploads/2018/12/nc.png'),
(23, NULL, 'Pickering College', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1842-01-01', 2, 15, 'https://globusedu.kz/canada/pickering-college/', 'https://globusedu.kz/wp-content/uploads/2019/10/Pickering-College.jpg'),
(24, NULL, 'Royal Roads University', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1995-01-01', 1, 16, 'https://globusedu.kz/canada/royal-roads-university/', 'https://globusedu.kz/wp-content/uploads/2019/09/Royal-Roads-University.jpg'),
(25, NULL, 'Rutherford Canadian School                      ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '2003-01-01', 2, 6, 'https://globusedu.kz/canada/rutherford-canadian-school/', 'https://globusedu.kz/wp-content/uploads/2019/09/Rutherford-Canadian-School.jpg'),
(26, NULL, 'SAIT Polytechnic', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1926-01-01', 1, 17, 'https://globusedu.kz/canada/sait/', 'https://globusedu.kz/wp-content/uploads/2019/09/SAIT-Polytechnic.jpg'),
(27, NULL, 'St.Lawrence College', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1879-01-01', 1, 14, 'https://globusedu.kz/canada/st-lawrence-college/', 'https://globusedu.kz/wp-content/uploads/2018/12/st-lawrence-college.jpg'),
(28, NULL, 'Seneca College                                 ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1967-01-01', 1, 6, 'https://globusedu.kz/canada/seneca-college/', 'https://globusedu.kz/wp-content/uploads/2019/10/Seneca-College.jpg'),
(29, NULL, 'Sheridan College', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1967-01-01', 1, 14, 'https://globusedu.kz/canada/sheridan-college/', 'https://globusedu.kz/wp-content/uploads/2019/09/Sheridan-College.jpg'),
(30, NULL, 'Thompson Rivers University                ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1970-01-01', 1, 18, 'https://globusedu.kz/canada/thompson-rivers-university/', 'https://globusedu.kz/wp-content/uploads/2018/12/Thompson-Rivers-University.jpg'),
(31, NULL, ' Trent University', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1964-01-01', 1, 19, 'https://globusedu.kz/canada/trent-university/', 'https://globusedu.kz/wp-content/uploads/2019/10/Trent-University.jpg'),
(32, NULL, 'Trinity College School', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1865-01-01', 2, 20, 'https://globusedu.kz/canada/trinity-college-school/', 'https://globusedu.kz/wp-content/uploads/2019/10/Trinity-College-School.jpg'),
(33, NULL, 'University of Victoria', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1963-01-01', 1, 16, 'https://globusedu.kz/canada/victoriauniversity/', 'https://globusedu.kz/wp-content/uploads/2018/11/uni_victoria.jpg'),
(34, NULL, 'University of Guelph', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1964-01-01', 1, 21, 'https://globusedu.kz/canada/university-of-guelph/', 'https://globusedu.kz/wp-content/uploads/2019/10/University-of-Guelph.jpg'),
(35, NULL, 'University of British Columbia ( UBC)', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1908-01-01', 1, 3, 'https://globusedu.kz/canada/university_of_british_columbia/', 'https://globusedu.kz/wp-content/uploads/2018/12/ubc.jpg'),
(36, NULL, 'International College of Manitoba (ICM) (University of Manitoba)', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1877-01-01', 1, 22, 'https://globusedu.kz/canada/international-college-of-manitoba/', 'https://globusedu.kz/wp-content/uploads/2019/10/Columbia-International-College-1.jpg'),
(37, NULL, 'University of Toronto', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '1827-01-01', 1, 6, 'https://globusedu.kz/canada/university-of-toronto/', 'https://globusedu.kz/wp-content/uploads/2019/10/University-of-Toronto.jpg'),
(38, NULL, 'UBC Vantage College                          ', NULL, 1, '2019-10-01 14:09:49', '2019-10-01 14:09:49', '2014-01-01', 1, 23, 'https://globusedu.kz/canada/vantage-college/', 'https://globusedu.kz/wp-content/uploads/2019/10/UBC-Vantage-College.jpg');

-- 
-- Dumping data for table specialty_copy
--
INSERT INTO specialty_copy VALUES
(1, 'Архитектура и строительство', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(2, 'Естественные науки', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(3, 'Искусство и дизайн', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(4, 'Социальные или общественные науки', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(5, 'Медицина и здоровье', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(6, 'Инженеринг', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(7, 'Бизнес и управление', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(8, 'Компьютерная наука и программирование', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(9, 'Туризм и гостиничное дело', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(10, 'Гуманитарные науки', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(11, 'Педагогика', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(12, 'Право', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20'),
(13, 'Авиация', NULL, NULL, '2019-09-12 17:02:20', '2019-09-12 17:02:20');

-- 
-- Dumping data for table specialty
--
INSERT INTO specialty VALUES
(1, 'Архитектура и строительство', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(2, 'Естественные науки', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(3, 'Искусство, анимация и дизайн', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(4, 'Социальные или общественные науки', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(5, 'Медицина и здравоохранение', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(6, 'Инженеринг', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(7, 'Бизнес и управление, менеджмент', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(8, 'Компьютерная наука и программирование', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(9, 'Туризм, гостиничное дело, кулинария', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(10, 'Гуманитарные науки', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(11, 'Педагогика', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(12, 'Право', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(13, 'Авиация', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15'),
(14, 'технические специальности', NULL, NULL, '2019-10-03 09:26:15', '2019-10-03 09:26:15');

-- 
-- Dumping data for table program_cpy01102019
--
-- Table learn.program_cpy01102019 does not contain any data (it is empty)

-- 
-- Dumping data for table program
--
INSERT INTO program VALUES
(1, 'среднее образование', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22'),
(2, 'бакалавриат (BA)', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22'),
(3, 'Магистратура и PhD', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22'),
(4, 'подготовка к бакалавриату', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22'),
(5, 'подготовка к магистратуре', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22'),
(6, 'языковые курсы', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22'),
(7, 'каникулярные программы', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22'),
(8, 'академический английский язык', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22'),
(9, ' постдипломные программы', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22'),
(10, 'дипломные и трансферная программы', NULL, NULL, '2019-10-01 16:18:22', '2019-10-01 16:18:22');

-- 
-- Dumping data for table log
--
INSERT INTO log VALUES
(1, '1, 2, 4', '2019-09-25 15:37:58'),
(2, 'select * from country', '2019-09-27 09:45:05'),
(3, 'select * from country\r\n    where id = 1', '2019-09-27 09:45:32'),
(4, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id =  and EXISTS (\r\n      select * from university_programs up \r\n      where \r\n        up.university_id = u.id \r\n        and up.program_id = ) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = ) order by u.name_en asc;', '2019-09-27 10:02:20'),
(5, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and EXISTS (\r\n      select * from university_programs up \r\n      where \r\n        up.university_id = u.id \r\n        and up.program_id = 2) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 10:05:36'),
(6, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 10:05:56'),
(7, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 10:15:25'),
(8, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 10:19:43'),
(9, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where EXISTS (\r\n      select * from university_programs up \r\n      where \r\n        up.university_id = u.id \r\n        and up.program_id = 2) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 10:19:54'),
(10, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 10:20:01'),
(11, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 10:20:09'),
(12, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-27 10:20:14'),
(13, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 3) order by u.name_en asc;', '2019-09-27 10:20:21'),
(14, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 10:20:25'),
(15, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:25:58'),
(16, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 EXISTS (\r\n      select * from university_programs up \r\n      where \r\n        up.university_id = u.id \r\n        and up.program_id = 1) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:26:08'),
(17, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and EXISTS (\r\n      select * from university_programs up \r\n      where \r\n        up.university_id = u.id \r\n        and up.program_id = 1) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:27:49'),
(18, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and EXISTS (\r\n      select * from university_programs up \r\n      where \r\n        up.university_id = u.id \r\n        and up.program_id = 1) and exists (\r\n      select * from university_specialities us\r\n      WHERE \r\n        us.university_id = u.id\r\n        and us.specialty_id = 1) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:28:38'),
(19, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_specialities us\r\n      WHERE \r\n        us.university_id = u.id\r\n        and us.specialty_id = 1) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:29:17'),
(20, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:57:14'),
(21, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:57:23'),
(22, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:58:18'),
(23, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_specialities us\r\n      WHERE \r\n        us.university_id = u.id\r\n        and us.specialty_id = 13) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:58:27'),
(24, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_specialities us\r\n      WHERE \r\n        us.university_id = u.id\r\n        and us.specialty_id = 1) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:58:41'),
(25, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 and exists (\r\n      select * from university_specialities us\r\n      WHERE \r\n        us.university_id = u.id\r\n        and us.specialty_id = 1) and exists (\r\n      select * from university_languages ul\r\n      WHERE \r\n        ul.university_id = u.id\r\n        and ul.language_id = 4) order by u.name_en asc;', '2019-09-27 11:59:18'),
(26, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id order by u.name_en asc;', '2019-09-27 14:36:28'),
(27, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id order by u.name_en asc;', '2019-09-27 14:38:10'),
(28, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id order by u.name_en asc;', '2019-09-27 14:38:16'),
(29, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id order by u.name_en asc;', '2019-09-27 14:39:14'),
(30, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id order by u.name_en asc;', '2019-09-27 14:39:20'),
(31, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id order by u.name_en asc;', '2019-09-27 14:39:23'),
(32, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id order by u.name_en asc;', '2019-09-27 14:40:05'),
(33, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id order by u.name_en asc;', '2019-09-27 14:40:49'),
(34, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id order by u.name_en asc;', '2019-09-27 14:42:20'),
(35, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:12:01'),
(36, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:14:53'),
(37, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:15:02'),
(38, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:16:03'),
(39, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:21:10'),
(40, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:23:46'),
(41, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:27:28'),
(42, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:34:20'),
(43, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:36:19'),
(44, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:37:28'),
(45, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:37:57'),
(46, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:38:24'),
(47, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:38:47'),
(48, 'select u.id, u.name_en ''name'', u.found, ut.name_ru ''type'', lc.name_ru ''location'', u.url, u.url_pic,\r\n     (select GROUP_CONCAT(ll.name_ru SEPARATOR '', '') from university_languages ul \r\n          join language ll on ll.id = ul.language_id \r\n      where ul.university_id = u.id \r\n         group by ul.university_id) ''languages'', \r\n    (select GROUP_CONCAT(pp.name_ru SEPARATOR '', '') from university_programs up1 \r\n          join program pp on pp.id = up1.program_id \r\n     where up1.university_id = u.id \r\n        group by up1.university_id) ''programs'' \r\n  from university u \r\n    join location lc on lc.id = u.location_id \r\n    join university_type ut on ut.id = u.type_id where u.country_id = 1 order by u.name_en asc;', '2019-09-30 11:39:07');

-- 
-- Dumping data for table location
--
INSERT INTO location VALUES
(1, '2019-09-25 11:36:59', '2019-09-25 12:31:17', 'г. Оттава, Канада', NULL, NULL),
(2, '2019-09-25 11:37:10', '2019-09-25 12:31:17', 'г. Бернаби и г. Ванкувер (Канада)', NULL, NULL),
(3, '2019-09-25 11:37:24', '2019-09-25 12:31:17', 'г. Ванкувер (Канада)', NULL, NULL),
(4, '2019-09-25 11:37:40', '2019-09-25 12:31:17', 'г. Сент-Катаринс провинции Онтарио (Канада)', NULL, NULL),
(5, '2019-09-25 00:00:00', '2019-09-25 12:31:17', 'г. Бёрнаби (Канада)', NULL, NULL),
(6, '2019-09-25 11:38:08', '2019-09-25 12:31:17', 'г. Торонто, Канада', NULL, NULL),
(7, '2019-09-25 11:38:27', '2019-09-25 12:31:17', 'г. Гамильтон (Канада)', NULL, NULL),
(8, '2019-09-25 11:38:47', '2019-09-25 12:31:17', 'г. Китченер (Канада)', NULL, NULL),
(9, '2019-09-25 11:38:57', '2019-09-25 12:31:17', 'г. Ошава (Канада)', NULL, NULL),
(10, '2019-09-25 11:39:04', '2019-09-25 12:31:17', 'г. Лондон (Канада)', NULL, NULL),
(11, '2019-09-25 11:39:13', '2019-09-25 12:31:17', 'г. Ванкувер, г. Виктория, г. Калгари  (Канада)', NULL, NULL),
(12, '2019-09-25 11:39:34', '2019-09-25 12:31:17', 'г. Торонто и г. Ванкувер (Канада)', NULL, NULL),
(13, '2019-09-25 11:39:43', '2019-09-25 12:31:17', 'г. Лейкфилд (Канада)', NULL, NULL),
(14, '2019-09-25 11:39:52', '2019-09-25 11:39:52', 'провинция Онтарио (Канада)', NULL, NULL),
(15, '2019-09-25 00:00:00', '2019-09-25 12:31:17', 'г. Ньюмаркет (Канада)', NULL, NULL),
(16, '2019-09-25 11:40:15', '2019-09-25 12:31:17', 'г. Виктория (Канада)', NULL, NULL),
(17, '2019-09-25 11:40:40', '2019-09-25 12:31:17', 'г. Калгари  (Канада)', NULL, NULL),
(18, '2019-09-25 11:40:55', '2019-09-25 12:31:17', 'г. Камлупс (Канада)', NULL, NULL),
(19, '2019-09-25 11:41:02', '2019-09-25 12:31:17', 'г. Питерборо (Канада)', NULL, NULL),
(20, '2019-09-25 11:41:08', '2019-09-25 12:31:17', 'г. Порт-Хоуп (Канада)', NULL, NULL);

-- 
-- Dumping data for table language
--
INSERT INTO language VALUES
(4, 'английский', NULL, NULL, '2019-09-25 12:09:20', '2019-09-25 12:09:20');

-- 
-- Dumping data for table country
--
INSERT INTO country VALUES
(1, 'Канада', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(2, 'Франция', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(3, 'Нидерланды', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(4, 'Великобритания', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(5, 'США', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(6, 'Новая зеландия', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(7, 'Ирландия', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(8, 'Турция', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(9, 'Сингапур', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(10, 'Малайзия', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(11, 'ОАЭ', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(12, 'Республика Корея', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(13, 'Швейцария', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08'),
(14, 'Австралия', NULL, NULL, '2019-09-12 16:57:08', '2019-09-12 16:57:08');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;